### PR TITLE
fix: move husky git message check to correct location

### PR DESCRIPTION
**Pull request by nulian**
While using this library as example for component set implementation for release notes I found out the commit message verification is broken.

### CODE REVIEW

**Comment by NiekBetty** [comment]
@nulian this commit message triggers a release for the package. Please change `fix` to `chore`

**Comment by nulian** [comment]
@NiekBetty Changed commit message to chore

**Comment by NiekBetty** [comment]
@nulian apperantly I don't know the commit rules I set up myself. It should be `build:...`. I'm sorry

**Comment by nulian** [comment]
hehe hope I have the correct commit message now :)

**Pull request merged**
